# ====================================================================
# TERMINAL COLORS & TEXT CAPABILITIES
# ====================================================================
# Tells Tmux to render full 24-bit RGB True Colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# Allows fancy undercurl lines (underlines under bad code syntax inside Neovim)
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setqc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%m'

# ====================================================================
# QUALITY OF LIFE BEHAVIORS
# ====================================================================
set -g mouse on               # Enables clicking tabs, dragging pane sizes, mouse scrolls
set -s escape-time 0          # Stops the annoying delayed pause when pressing 'Esc' in Vim
set -g history-limit 50000     # Bumps terminal buffer memory up from 2,000 lines to 50,000

# Changes window indices to start matching keyboard layout (1 to 9 instead of 0 to 9)
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on # Automatically slides remaining window indexes left if one closes

# Configures tmux core options and panel borders to match a minimalist scheme
set -g message-style bg=black,fg=cyan,bold
set -g mode-style bg=brightblack,fg=white,bold

# ====================================================================
# TMUX PLUGINS & INTERACTIVE THEMING
# ====================================================================
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Injecting the Catppuccin theme module variables
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor 'mocha'              # Options: latte, frappe, macchiato, mocha
set -g @catppuccin_window_status_style "rounded" # Wraps active workspaces in rounded tabs

# Executes the Tmux Plugin Manager script engine (MUST STAY ON THE ABSOLUTE BOTTOM LINE)
run '~/.tmux/plugins/tpm/tpm'

